[package]
edition = "2018"
name = "zksync_verification_key_generator_and_server"
version = "1.0.0"

[lib]
name = "zksync_verification_key_server"
path = "src/lib.rs"

[[bin]]
name = "zksync_verification_key_generator"
path = "src/main.rs"

[[bin]]
name = "zksync_json_to_binary_vk_converter"
path = "src/json_to_binary_vk_converter.rs"

[[bin]]
name = "zksync_commitment_generator"
path = "src/commitment_generator.rs"

[dependencies]
bincode = "1.3.3"
circuit_testing = {git = "https://github.com/matter-labs/era-circuit_testing.git", branch = "main"}
itertools = "0.10.5"
vlog = {path = "../../lib/vlog", version = "1.0"}
zksync_types = {path = "../../lib/types", version = "1.0"}

ff = {package = "ff_ce", version = "0.14.1"}
hex = "0.4.3"
serde_json = "1.0.85"
structopt = "0.3.26"
toml_edit = "0.14.4"
